default:
  image:
    name: hashicorp/terraform:light
    entrypoint: [""]

  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - .terraform

variables:
  PLAN: plan.tfplan
  PLAN_FILE_JSON: tfplan.json
  TF_CLOUD_CREDENTIALS: |
    credentials "app.terraform.io" {
      token = "${TF_TOKEN}"
    }

before_script:
  - apk --no-cache add jq
  - alias convert_report="jq -r '([.resource_changes[]?.change.actions?]|flatten)|{\"create\":(map(select(.==\"create\"))|length),\"update\":(map(select(.==\"update\"))|length),\"delete\":(map(select(.==\"delete\"))|length)}'"
  - terraform --version
  - echo "${TF_CLOUD_CREDENTIALS}" > "${HOME}/.terraformrc"
  - terraform init

stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - terraform validate
  tags:
    - dev

plan:
  stage: plan
  script:
    - terraform plan -out $PLAN 
    - terraform show -json $PLAN | convert_report > $PLAN_FILE_JSON
  dependencies:
    - validate
  artifacts:
    reports:
      terraform: ${PLAN_FILE_JSON}
    paths:
      - ${PLAN}
  tags:
    - dev

apply:
  stage: apply
  script:
    - terraform apply $PLAN
  dependencies:
    - plan
  when: manual
  tags:
    - dev

destroy:
  stage: destroy
  script:
    - terraform plan -destroy -out $PLAN
    - terraform apply -destroy $PLAN
  when: manual
  tags:
    - dev