variables:
  TF_CLOUD_CREDENTIALS: |
    credentials "app.terraform.io" {
      token = "${TF_TOKEN}"
    }

stages:
  - validate
  - plan
  - apply

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - terraform --version
  - echo "${TF_CLOUD_CREDENTIALS}" > "${HOME}/.terraformrc"
  - terraform init

cache:
  key: terraform
  paths:
    - .terraform

validate:
  stage: validate
  script:
    - terraform validate
  tags:
    - dev

plan:
  stage: plan
  script:
    - terraform plan -out "tfplan"
  dependencies:
    - validate
  artifacts:
    paths:
      - tfplan
  tags:
    - dev

apply:
  stage: apply
  script:
    - terraform apply -input=false "tfplan"
  dependencies:
    - plan
  when: manual
  tags:
    - dev